### ISSUE TITLE
Create a website

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#142]
Things I want for the first release:
- A clear overview of each feature in VSDiagostics including .gifs that demonstrate the usage
- General information about the project, contribution stuff, contact, etc
- Changelog information per release
- A service that allows the user to upload a solution or one-or-more source files to provide a sort of analysis on the go. The result shown to the user should consist of a summary of each warning produced by VSDiagnostics and a download link for the transformed files. When separate sourcefiles were uploaded, the changes should be visible in the browser as well.

This is a rather ambitious project and I'd like to put myself behind this to get experience with the relevant technologies. When the project is underway, I imagine I'll open this to other collaborators as well though.

This is a blocking feature that will be a requirement to release v2.0.0, which will go paired with some "advertising" on social media/news platforms.

**Comment by Vannevelj** [comment]
First awesome mockup for the index page:

![index](https://cloud.githubusercontent.com/assets/2777107/12758840/7aaa587a-c9de-11e5-9d75-f1974a8308a1.png)

**Comment by ckuhn203** [comment]
What are the "relevant technologies"? I'm spending my days doing web dev these days, so feel free to ping me if you need any assistance/advice.

**Comment by Vannevelj** [comment]
I'm building it with plain HTML/CSS/JS and no backend (at least: initially). Also, I'm avoiding all JS libraries so I can get a solid grasp on the basics. 
You can find the appropriate repository here: https://github.com/VSDiagnostics/VSDiagnostics.github.io

At a later stage I will also move this repository to that organization.

**Comment by ckuhn203** [comment]
Cool. I'm assuming some kind of .Net web service backing the Diagnostics at some point?

**Comment by Vannevelj** [comment]
Yeah, once I start working on integrating that online tool then that will probably come with a .NET backend. That will probably come after the site's release though

**Comment by Vannevelj** [comment]
Design for the "Diagnostics" page:

![index - copy](https://cloud.githubusercontent.com/assets/2777107/12802634/99242c3e-cae4-11e5-8762-f7cc8bdc8090.png)

**Comment by Vannevelj** [comment]
Will not spend on this.
