### ISSUE TITLE
Implement FlagsEnumWithPowersOfTwo analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#143]
This should show a warning because it has the `[Flags]` attribute but contains a non-power of two (or 0) value.

	[Flags]
	enum X 
	{
		A = 0,
		B = 1,
		C = 2,
		D = 3
	}

Instead it should become

	[Flags]
	enum X 
	{
		A = 0,
		B = 1,
		C = 2,
		D = 4
	}

**Comment by Vannevelj** [comment]
This should also account for enum options without an explicit value.

**Comment by Hosch250** [comment]
There are a couple different options for the code fix here.

Initial enum:

    [Flags]
    enum X 
    {
        A = 0,
        B = 1,
        C = 2,
        D = 3,
        E = 4,
        F = 5,
        G = 6,
        H = 7,
        I = 8
    }

1) Adjust in order of entering:

    [Flags]
    enum X 
    {
        A = 0,
        B = 1,
        C = 2,
        D = 4,
        E = 8,
        F = 16,
        G = 32,
        H = 64,
        I = 128
    }

2) Change bad values only:

    [Flags]
    enum X 
    {
        A = 0,
        B = 1,
        C = 2,
        D = 16,
        E = 4,
        F = 32,
        G = 64,
        H = 128,
        I = 8
    }

3) Adjust all values after bad value:

    [Flags]
    enum X 
    {
        A = 0,
        B = 1,
        C = 2,
        D = 4,
        E = 8,
        F = 16,
        G = 32,
        H = 64,
        I = 128
    }

This is slightly different than 1) in the following scenario:

    [Flags]
    enum X 
    {
        A = 8,
        B = 4,
        C = 2,
        D = 1,
        E = 0,
        F = 3,
        G = 5,
        H = 6,
        I = 7
    }

Becomes:

    [Flags]
    enum X 
    {
        A = 8,
        B = 4,
        C = 2,
        D = 1,
        E = 0,
        F = 16,
        G = 32,
        H = 64,
        I = 128
    }

**Comment by Vannevelj** [comment]
I would suggest that we simply change everything in the order it's in the enum. We're already introducing a build-breaking change, might as well do it in order then.

This is also one of the areas we can expand on later when we implement user-specified settings.

**Comment by Hosch250** [comment]
Only examines positive and negative values. Bitshifting and other numeric operations are too complex to analyze without a tool to compile the EqualsValue expression to a number.
