### ISSUE TITLE
Implement EnumToFlagsEnum analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#144]
Given an enum, provide a code fix to turn it into a flagged enum (no warning should be shown).

The following scenario:

	enum X 
	{
		A = 1,
		B = 2,
		C = 7,
		D = 58
	}

becomes

	[Flags]
	enum X 
	{
		A = 0,
		B = 1,
		C = 2,
		D = 4
	}

**Comment by Hosch250** [comment]
Should we just add the `[Flags]` attribute here and let the other inspection (#143) handle the values that aren't powers of two?

**Comment by Vannevelj** [comment]
I would suggest we simply add the `[Flags]` attribute and call the codefix from the other analyzer (if needed). You can share a lot of code between those two diagnostics.
