### ISSUE TITLE
Implement SwitchStatementWithoutDefaultBlock

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#150]
`switch` statements their `default` block is optional but I believe it should always be included, at the very least to indicate in what scenario none of the `case` blocks would have been hit.

I would suggest to add a code fix that adds the following block (or a similar message):

    default: // This should or shouldn't get hit because..

**Comment by Hosch250** [comment]
What about when we are switching over an enum and all cases are covered?

**Comment by Vannevelj** [comment]
I would still show the warning -- the developer might add another enum value and forget to include it in the switch. This way it would show up early since he'd see the thrown exception. On that note: I suggest we throw some kind of exception from the `default` block. Perhaps `ArgumentException`?

**Comment by Hosch250** [comment]
What about `NotImplementedException()`?

**Comment by Vannevelj** [comment]
mm both apply, I suppose. I like `ArgumentException` here more though because it explicitly states that a value is passed in that we didn't expect before.
