### ISSUE TITLE
Namingconventions clash with existing variables

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#200]
When you have an incorrectly named variable and apply the Code Fix, it might interfere with a different variable that already exists. We have to come up with an appropriate solution: show a warning? Show nothing? Don't provide a code fix? Change the name to something like `variable1` (aka: a suffix)?

**Comment by Hosch250** [comment]
I'm for providing a warning, but not a code fix.

**Comment by Vannevelj** [comment]
I agree, let's do that.

**Comment by Vannevelj** [comment]
As discussed: let's make two `Rule` properties -- one for the traditional situation and one in case of a conflicting variable. We can let the code fix work of the traditional one to avoid showing a fix when it shouldn't (but we do still want a warning).
