### ISSUE TITLE
Explicit Access Modifier

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#205]
When the class derives from an interface, it appears to mess the class and method inspection results up.  Possibly others as well.  Definitely need some tests for this.

**Comment by Hosch250** [comment]
Restarting the solution made everything work again, and I can't re-reproduce it. :frowning:

**Comment by Hosch250** [comment]
Still no repro on smaller solutions, but on Rubberduck, it works for members that need the modifier when the solution is opened, but does not work otherwise.  Also, even though the analyzer runs, it doesn't always update the message/warning.  I'm running it with warning level so I can see exactly what is happening.

**Comment by Hosch250** [comment]
Fixed by PR #209

**Comment by Hosch250** [comment]
Not fixed by PR #209 after all.

**Comment by Hosch250** [comment]
After some research, it is the `ArgumentExceptionWithoutNameofOperatorAnalyzer` causing the problem on my machine.  I can't test the code fix without the analyzer, so....

**Comment by Vannevelj** [comment]
As it turns out, there was an infinite loop in `Extensions.InheritsFrom` because we looked through the type hierarchy for a type's basetype not knowing that `object.BaseType` and `ValueType.BaseType` returned `Object` and `ValueType` respectively.
