### ISSUE TITLE
Implement AmbiguousNewGuid

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#207]
When someone writes `new Guid()` they receive an empty guid (all values are 0). I see two reasons to write this:
- To create an empty guid
- To generate a new guid

both of which can be distinguished better using
- `Guid.Empty`
- `Guid.NewGuid()`

I suggest we make a code fix that provides both options (and shows a warning). That way the user can choose which one they intend to use.

**Comment by Hosch250** [comment]
That is a typo - that commit has nothing to do with this issue.
