### ISSUE TITLE
Implement SwitchDoesNotHandleAllEnumOptions

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#211]
Show a warning when we `switch` over an enum but not all enum options are covered by a `case` statement. I would also add a code fix that inserts the missing ones.

For example:

	void Main()
	{
		var e = MyEnum.A;
		switch(e)
		{
			case A: break;
			case B: break;
			default: break;
		}
	}
	
	enum MyEnum
	{
		A,
		B,
		C
	}

**Comment by Vannevelj** [comment]
Related to #375

**Comment by Hosch250** [comment]
Should the code fix for this just be:

```
case option:
    break;
```

**Comment by Vannevelj** [comment]
I would add a body: 

```csharp
case option:
   throw new NotImplementedException();
   break;
```
