### ISSUE TITLE
Attributes and `nameof()`

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#212]
At the top of every code fix, we put an attribute similar to this:

    [ExportCodeFixProvider("ExplicitAccessModifiers", LanguageNames.CSharp), Shared]

This is the attribute for `ExplicitAccessModifiersCodeFix`.  Would it be possible to replace this hard-coded string with `nameof(ExplicitAccessModifiersCodeFix)`?

**Comment by Vannevelj** [comment]
`nameof()` is a compile-time construct so that should be no problem.
