### ISSUE TITLE
Implement UseAliasesInsteadOfConcreteType analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#22]
`String` becomes `string`
`Int64` becomes `long`
`Int32` becomes `int`
`UInt64` becomes `ulong`

etc.

**Comment by Hosch250** [comment]
Others for reference:

`SByte` → `byte`
`Byte` → `byte`
`Double` → `double`
`Decimal` → `decimal`
`Object` → `object`
`Int16` → `short`
`UInt16` → `ushort`
`UInt32` → `uint`
`Boolean` → `bool`
`Char` → `char`
`Single` → `float`
`String` → `string`
`Int64` → `long`
`Int32` → `int`
`UInt64` → `ulong`
