### ISSUE TITLE
Implement IntegerDivisionByInteger

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#236]
When dividing two integers, the fraction is truncated from the result effectively resulting in a rounding. Figure out what the equivalent is in a more expressive way and provide a warning + code fix.

I imagine it might turn from this:

    int x = 5;
    int y = 6;
    double z = 5 / 6;

to this:

    int x = 5;
    int y = 6;
    double z = Math.Floor((double) 5 / (double) 6);

Completely untested and I might be making things up, but you get the idea.

**Comment by Hosch250** [comment]
This will need lot of test cases:

```
int x = 5 / 6;
var x = 5 / 6;
double x = 5 / 6;
var x = (double) (5 / 6);
var x = (int) (5 / 6);
var x = 5 / 6 - 3;
var x = 3 + 5 / 6;
var x = 3 == 5 / 6;

void Foo (int x) {}
Foo (5 / 6);

void Foo (double x) {}
Foo (5 / 6);
```

Any others?

**Comment by Vannevelj** [comment]
Actually, I don't think we need the code fix as laid out in the first post since it is most likely a hidden problem and not intended to work like this. Just casting one of the arguments to a double should suffice as fix.
