### ISSUE TITLE
Support for VBDiagnostics Analyzers

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#251]
Many of our diagnostics can probably support Visual Basic with no change except for adding the language in the attribute.  The biggest issue will be writing unit tests for them all.

**Comment by Vannevelj** [comment]
I'm not familiar with VB.NET so I'm not sure what would be considered best practice there. However feel free to write tests for the ones you're interested in and we'll make them available.

**Comment by Hosch250** [comment]
The tests that these would work well with are:

## As sure as I can get with my knowledge of VB.NET

AttributeWithEmptyArgumentList
EnumCanHaveFlagsAttribute
ObsoleteAttributeWithoutReason
ArgumentExceptionWithoutNameofOperator 
CatchNullReferenceException
EmptyArgumentException
EmptyCatchClause
RethrowExceptionWithoutLosingStacktrace
SingleGeneralException
 CompareBooleanToFalseLiteral
CompareBooleanToTrueLiteral
ConditionIsAlwaysFalse
ConditionIsAlwaysTrue
ConditionalOperatorReturnsDefaultOptions
ConditionalOperatorReturnsInvertedDefaultOptions
ExplicitAccessModifiers
FlagsEnumValuesAreNotPowersOfTwo
GotoDetection
NamingConventions
OnPropertyChangedWithoutNameOfOperator
SingleEmptyConstructor
ReplaceEmptyStringWithStringDotEmpty
StringPlaceholdersInWrongOrder
RemoveTestSuffix
TestMethodWithoutPublicModifier
OnPropertyChangedWithoutCallerMemberName

**Comment by Vannevelj** [comment]
I would like to see a separate issue for each VB diagnostic we intend to implement. This makes it a lot easier to keep track of the progress.
