### ISSUE TITLE
Simplify alias lookup through simplifier

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#269]
I think we're using a lookup table to map explicit types to aliases. We should be able to simplify this using the `Simplifier`.  

https://github.com/dotnet/roslyn/blob/a4290a6f38316641b6aea1f693d19f40bcb7c35e/src/Workspaces/Core/Portable/Simplification/Simplifier.cs

**Comment by Vannevelj** [comment]
That being said -- it's probably a more expensive operation so look into the internals first.

**Comment by SLaks** [comment]
The internals is http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ExpressionSyntaxExtensions.cs,2251

**Comment by Vannevelj** [comment]
Done in #487
