### ISSUE TITLE
Implement RemoveTestSuffix analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#27]
Tests are denoted using an attribute in most common and recent .NET testing frameworks. Appending "Test" is redundant.

**Comment by Vannevelj** [comment]
I'm delaying this to a next release. I'm leaving on vacation soon and I want 1.7.0 to be released so a bunch of bugs are taken care of.

**Comment by Hosch250** [comment]
Does this apply to test methods, test classes, or both?

**Comment by Vannevelj** [comment]
Only test methods (aka: methods annotated with `[Test]`, `[TestMethod]` and `[Fact]`).
