### ISSUE TITLE
NullReferenceException on AsyncMethodWithoutAsyncSuffixAnalyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#288]
Showed up as an 'info' message with the following stacktrace:

	Message AD0001  Analyzer 'VSDiagnostics.Diagnostics.Async.AsyncMethodWithoutAsyncSuffix.AsyncMethodWithoutAsyncSuffixAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.Enyim.Caching       1   Active Analyzer 'VSDiagnostics.Diagnostics.Async.AsyncMethodWithoutAsyncSuffix.AsyncMethodWithoutAsyncSuffixAnalyzer' threw the following exception:
	'System.NullReferenceException: Object reference not set to an instance of an object.
	   at VSDiagnostics.Diagnostics.Async.AsyncMethodWithoutAsyncSuffix.AsyncMethodWithoutAsyncSuffixAnalyzer.<>c__DisplayClass10_0.<IsDefinedInAncestor>b__0(ISymbol method)
	   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
	   at VSDiagnostics.Diagnostics.Async.AsyncMethodWithoutAsyncSuffix.AsyncMethodWithoutAsyncSuffixAnalyzer.IsDefinedInAncestor(IMethodSymbol methodSymbol)
	   at VSDiagnostics.Diagnostics.Async.AsyncMethodWithoutAsyncSuffix.AsyncMethodWithoutAsyncSuffixAnalyzer.AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context)
	   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass38_1`1.<ExecuteSyntaxNodeAction>b__1()
	   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

Project: EnyimMemcached https://github.com/enyim/EnyimMemcached
             ServiceStack.Redis https://github.com/ServiceStack/ServiceStack.Redis

**Comment by Vannevelj** [comment]
I'm re-opening this because we haven't explicitly checked that it has been fixed with the above referenced commit

**Comment by Vannevelj** [comment]
After moving this to an extension method and presumably re-using it in #23 it now also crashes as soon as you open the Roslyn solution

**Comment by tiesmaster** [comment]
That's crappy to hear :unamused:

Maybe I can spend some time on this. How did you encounter this exactly? Are you running the analyzer as VSIX or as analyzer for a particular project. And do remember which in which file this was?

**Comment by Vannevelj** [comment]
I believe I encountered it after I commented out some stuff for #324. Maybe there was a connection? As soon as you open the Roslyn solution (https://github.com/dotnet/roslyn), it will throw a NRE because of the previously mentioned problem so I had to work around that quickly. In order to fix this error I suggest we fix #324 first so we can see if it's still a problem

**Comment by tiesmaster** [comment]
Ok, that looks like a good plan. Let me know if you get some more specifics on this.

Good luck with your paper. I read about it in the Gitter chat of Roslyn room. I'd be interested in reading it as well ;)

**Comment by Vannevelj** [comment]
Just writing down some thoughts for future reference.

`containingType.FindImplementationForInterfaceMember` can return `null`:

    /// <summary>
    /// Returns the corresponding symbol in this type or a base type that implements
    ///             interfaceMember (either implicitly or explicitly), or null if no such symbol exists
    ///             (which might be either because this type doesn't implement the container of
    ///             interfaceMember, or this type doesn't supply a member that successfully implements
    ///             interfaceMember).
    /// 
    /// </summary>

The method that's being verified at the time of my current debugging session is 

> Method System.Boolean Microsoft.CodeAnalysis.CompilerServer.UnitTests.MockEngine.BuildProjectFile(System.String projectFileName, System.String[] targetNames, System.Collections.IDictionary globalProperties, System.Collections.IDictionary targetOutputs)

This turns out be a method implemented from `IBuildEngine` which is defined in an external assembly.

**Comment by Vannevelj** [comment]
Fixed in #360
