### ISSUE TITLE
Implement CompareBooleanToFalseLiteral analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#29]
Turn this:

    if(condition == false)

into this:

    if(!condition)

**Comment by Vannevelj** [comment]
Tricky scenario: a `Nullable<bool>` that is compared to `==  false` cannot be changed to `!b` since that would cause the following error:

> Cannot implicitly convert type 'bool?' to 'bool'. An explicit conversion exists (are you missing a cast?)

**Comment by Hosch250** [comment]
@Vannevelj This can be closed now.

**Comment by Vannevelj** [comment]
Implemented in #114 by @Hosch250
