### ISSUE TITLE
No rename IDE helper when renaming a method that already exists

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#297]
When a method violates naming conventions and is renamed, it won't give us the 'rename' IDE helper. Created error codes:

> CS0111	Type 'RedisClient' already defines a member called 'StoreAll' with the same parameter types
> CS0121	The call is ambiguous between the following methods or properties: 'RedisClient.StoreAll<TEntity>(IEnumerable<TEntity>)' and 'RedisClient.StoreAll<TEntity>(IEnumerable<TEntity>)'

**Comment by Vannevelj** [comment]
According to @sharwell CS0100 and CS0136 are also not accounted for thus far.

**Comment by sharwell** [comment]
Also CS0158, CS0140, CS0542, CS0249, CS0229, CS0202

**Comment by Vannevelj** [comment]
Additionally: CS0135, CS0104, CS0316, CS0412, CS0473, CS1061

**Comment by Vannevelj** [comment]
The above commit addresses all of the above mentioned error codes except CS0249. This is the only error that does not contain the renamed member in its message but that's not an issue because in the end, this situation is very unlikely to occur in the first place. The only way to have it if you have an `override void` method without any parameters and rename it to `Finalize` -- rather unlikely. Until there is a better way to do this hesitant renaming, I'm okay with this hidden bug being there.
