### ISSUE TITLE
Create new project for VB.NET analyzers

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#340]
When I was originally adding VB.NET analyzers, the compiler could not always tell which methods I was calling due to the members with identical names in different referenced namespaces.  Using a separate project would fix this issue, as well as have a clean organization of the analyzers.

**Comment by Vannevelj** [comment]
We don't do any VB.NET analyzers -- the next version of the analyzer API will provide language-agnostic IOperation interfaces that should take care of this automatically.

**Comment by Vannevelj** [comment]
See #486
