### ISSUE TITLE
NullReferenceException in FlagsEnumValuesAreNotPowersOfTwoAnalyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#347]
On these lines, `value` is `null`:

```csharp
var symbol = context.SemanticModel.GetDeclaredSymbol(member);
var value = symbol.ConstantValue;

switch (value.GetType().Name)
```

`symbol` here is `Field Microsoft.CodeAnalysis.FusionAssemblyIdentity.ASM_DISPLAYF.VERSION`. `member` is `EnumMemberDeclarationSyntax EnumMemberDeclaration VERSION = 0x01`

**Comment by Hosch250** [comment]
For permanent reference: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Shared/GlobalAssemblyCacheHelpers/FusionAssemblyIdentity.cs

**Comment by Hosch250** [comment]
It appears this is an issue when the value has a return clause, but no statement:

    foo = 

instead of

    foo = 1
