### ISSUE TITLE
Null Reference Exception in IsDefinedInAncestor

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#354]
See https://github.com/Vannevelj/VSDiagnostics/blob/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/Extensions.cs#L163

In https://github.com/ServiceStack/ServiceStack.Redis

**Comment by Vannevelj** [comment]
Duplicate of https://github.com/Vannevelj/VSDiagnostics/issues/288
