### ISSUE TITLE
Alias resolving is ambiguous when writing shitty code

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#408]
When you add this using directive:

    using Single = System.Double;

and use it as such:

    Single x = 10;

the warning message will say 

> Use alias float instead of concrete type Single.

while the code fix will suggest to turn it into `double`

**Comment by Hosch250** [comment]
I am changing this to reflect the real types, so this will say:

> Use alias double instead of concrete type Double.
