### ISSUE TITLE
Expand ConditionIsAlwaysTrue/False to constant expressions

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#410]
`ConditionIsAlwaysFalse`/ `ConditionIsAlwaysTrue` can both be improved by checking whether the expression itself is a constant value. This would also allow us to check for something like this as well:

    private const bool x = true;
    if(x == true) { }

Instead of restricting us to `if(true)` and `if(false)`.

**Comment by Hosch250** [comment]
We already do evaluate comparisons to literals.

    if(x == true) { }

However, we should be able to evaluate this as always true:

    private const bool x = true;
    if(x) { }

**Comment by Vannevelj** [comment]
Perhaps I should have used a different example. I meant this:

    private const int x = 5;
    if(x == 5) { }

**Comment by Hosch250** [comment]
OK, we should be able to check for both.
