### ISSUE TITLE
Is to As + null check crash

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#490]
VSDiagnostics crashes itself when trying to convert the following code to use `as` with a null check:

    var expression = firstStatement is ExpressionStatementSyntax
        ? ((ExpressionStatementSyntax) firstStatement).Expression
        : ((ReturnStatementSyntax) firstStatement).Expression;

**Comment by Vannevelj** [comment]
Also check in case of `return x is Y` (and basically any other scenario where a boolean expression is allowed)

**Comment by Hosch250** [comment]
Did you just merge the fix to this?

**Comment by Vannevelj** [comment]
To this particular example in our code: yes. But not the general issue with this bug (analyzer itself isn't fixed yet)

**Comment by Vannevelj** [comment]
Been doing some debugging work on this -- I believe it might be caused by the unrelated `if` statement above it. My notes on the subject thus far:

# Extracting is/as to try-cast

1. This triggers the analyzer wrongfully and produces incorrect code (but the analyzer works)

```
var method = statement.AncestorsAndSelf().OfType<MethodDeclarationSyntax>().FirstOrDefault();
if (method != null)
{
    var firstStatement = method.Body.Statements.First();
    var expression = firstStatement is ExpressionStatementSyntax
                    ? ((ExpressionStatementSyntax) firstStatement).Expression
                    : null;
}
```

2. This triggers the analyzer wrongfully and crashes the analyzer

```
var method = statement.AncestorsAndSelf().OfType<MethodDeclarationSyntax>().FirstOrDefault();
if (method != null)
{
    var firstStatement = method.Body.Statements.First();
    var expression = firstStatement is ExpressionStatementSyntax
                    ? ((ExpressionStatementSyntax) firstStatement).Expression
                    : ((ReturnStatementSyntax) firstStatement).Expression;
}
```

Possible stacktrace:

> 'editor.GetChangedDocument().GetTextAsync().Result' threw an exception of type 'System.NullReferenceException'
>     Data: {System.Collections.ListDictionaryInternal}
>     HResult: -2147467261
>     HelpLink: null
>     InnerException: null
>     Message: "Object reference not set to an instance of an object."
>     Source: "Microsoft.CodeAnalysis.CSharp.Workspaces"
>     StackTrace: "   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.RemoveNode(SyntaxNode root, SyntaxNode node, SyntaxRemoveOptions options)\r\n   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.RemoveChange.Apply(SyntaxNode root, SyntaxGenerator generator)\r\n   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()\r\n   at Microsoft.CodeAnalysis.Editing.DocumentEditor.GetChangedDocument()"
>     TargetSite: {Microsoft.CodeAnalysis.SyntaxNode RemoveNode(Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.SyntaxRemoveOptions)}

Used example code:

    void Method(object o)
    {
        if(true)
        {
            var res = o is int ? (int)o : (double)o;
        }
    }
