### ISSUE TITLE
Implement TypeToVar analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#5]
When a local variable is instantiated without `var`, offer a Code Fix to use `var` instead.

**Comment by ragnarok56** [comment]
I was working on a TypeToVar analyzer, and came across a scenario that maybe shouldn't suggest a fix...  this is somewhat contrived:

```
    class MyClass
    {
        void Method()
        {
            string x = new test();
        }
    }

    class test
    { 
        public static implicit operator string(test x)
        {
            return string.Empty;
        }
    }
```

perhaps user defined implicit conversions aren't suggested, but other implicit/explicit conversions are?

**Comment by Vannevelj** [comment]
I would suggest we only do it for types that are identical. Otherwise you'll encounter the same problem with `double x = 1;` where the type suddenly changes to an `int` if you use `var`. The same thing goes for subclasses: `Base x = new Sub();`.
