### ISSUE TITLE
Make TryCastWithoutUsingAsNotNull contextual

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#517]
Fun fun. Apparently 

```csharp
object o = 5;
if(o is int)
    var x = (int) o;
```

is around 6-7 times faster than

```csharp
object o = 5;
var oAsInt = o as int?;
if(oAsInt != null)
```

We should probably just make it a contextual option.

**Comment by Hosch250** [comment]
Is this only for nullable types, or always?

**Comment by Vannevelj** [comment]
Always, as you can see from this test code: http://stackoverflow.com/questions/1583050/performance-surprise-with-as-and-nullable-types
In the benchmark it uses a combination of `null` values, integers and strings but I receive similar results if I just use strings.

**Comment by Hosch250** [comment]
Hmm.  This is very interesting.
