### ISSUE TITLE
SwitchDoesNotHandleAllEnumOptions fails when using cast integer

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#520]
The following code breaks this fix:

    var e = FileMode.Append;
    switch (e)
    {
        case (FileMode)4:
            throw new System.NotImplementedException();
    }

It generates all members, including the item with value `4`, which is uncompilable.

**Comment by Hosch250** [comment]
Would it be an acceptable solution to not display the warning on this?

**Comment by Vannevelj** [comment]
Yeah, that's fine for me. Otherwise we'd have to make too many assumptions about how the user wants their code
