### ISSUE TITLE
Implement GetHashCodeRefersToMutableField

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#559]
see https://msdn.microsoft.com/en-us/library/system.object.gethashcode%28v=vs.110%29.aspx

> you should override GetHashCode only if 
> - You can compute the hash code from fields that are not mutable

This includes fields and properties. A mutable field is any field or property that is a reference type. Basically: we can accept any value type.
We can also augment this by allowing every `readonly` class that is deemed to be immutable. We don't do `const` fields because they have -- by definition -- the same value across all instances.

**Comment by Hosch250** [comment]
So, this should report for any non-readonly class and any non-value type, except for the immutable `System.String`?

**Comment by Vannevelj** [comment]
Euhm, it should basically be the same check as for https://github.com/VSDiagnostics/VSDiagnostics/issues/477#issuecomment-217932543

Show a warning when `GetHashCode()`:

* Contains a field that is not `readonly`
* Contains a property with a setter
* Contains a property with a getter that has an implementation
* A `class` (that is not `string`) is used
* Refers to a `static` or `const` field
