### ISSUE TITLE
Incorrect use of cancellation token

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#609]
We use the following pattern _everywhere_ in our code.  We are not supposed to use the `context.CancellationToken` here, but rather the cancellation token `x`.

```
context.RegisterCodeFix(
    CodeAction.Create("Title",
                x => DoFixAsync(context.Document, methodDeclaration, root, context.CancellationToken), "Id"), 
                diagnostic);
```

**Comment by Vannevelj** [comment]
Do you have some background information on this?

**Comment by Hosch250** [comment]
This is how the Roslyn team told me to do it when I was implementing code fixes for them.

**Comment by Vannevelj** [comment]
Well that's not enough to change the existing code though. Can you get some more info on it? I don't want to make changes based on hearsay

**Comment by Hosch250** [comment]
One comment: https://github.com/dotnet/roslyn/pull/12902#r73414166
Another: https://github.com/dotnet/roslyn/pull/12902#r73414285
Here is a comment about `context.CancellationToken`: https://github.com/dotnet/roslyn/pull/12997#r74368743

**Comment by Vannevelj** [comment]
Alright, good enough for me. Would be helpful to know the difference between these though
