### ISSUE TITLE
namingconvention

### ISSUE THREAD

**Issue by kannan09** [Vannevelj/VSDiagnostics#648]
i used your developed code for naming convention finally publish code to microsoft market place then after i download that vsix package from visual studio .it will not working properly in code fix.please give a better suggestion .

note : when i debug locally its working fine. only issue happened after publish market place the download package from visual studio.

**Comment by Vannevelj** [comment]
I won't support someone else publishing my code as their own VS extension. Once you get it to work, however, you're welcome to contributing it to this repo and I will release it.
