### ISSUE TITLE
Test project fails on build after forking

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#66]
Might be related to dependencies of the test project?

**Comment by ckuhn203** [comment]
I personally didn't have the nightly Roslyn builds in my NuGet feed. Once I added it, I was able to get the project to restore the packages and build. Although the build was successful, I still receive an error about NuGet not being able to restore `Microsoft.CodeAnalysis.CSharp.Workspaces` and some warnings related to that assembly.

**Comment by Vannevelj** [comment]
Just kidding, this is still a problem apparently.

**Comment by Vannevelj** [comment]
Yay, it works. Again. Solution: add the roslyn nightly builds NuGet package repository as a source.
