### ISSUE TITLE
Localize string resources

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#84]
It has to happen some time.

**Comment by Hosch250** [comment]
Do you want me to localize the `private const string Category = "General";`-type strings too?  What about displaying hard-coded keywords, like `"private"`?

**Comment by Vannevelj** [comment]
What I mean with resources are the fields "Category", "Message" and "Title", nothing else. I'm not entirely sure how this will play out with the const fields though.

**Comment by Hosch250** [comment]
I tried doing `Message` and `Title` already.  It failed: `Value must be compile-time constant.`

**Comment by Vannevelj** [comment]
Yeah, that's because those field are marked as `const`. You'll have to change them to `static` instead

**Comment by Hosch250** [comment]
When I try to localize the title for the CodeAction, it doesn't show up in the list anymore.

This works:

    CodeAction.Create("Add Modifier", ...)

While this does not:

    CodeAction.Create(VSDiagnosticsResources.IForgotTheExactKey, ...)
