### ISSUE TITLE
Reference ourselves

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#85]
I want VSDiagnostics to be an example implementation of VSDiagnostics. Reference the NuGet package and fix all issues we find (I know there are several violations already).

Word of caution: I've noticed that sometimes after adding the VSDiagnostics NuGet package, the solution doesn't build anymore. If this occurs, go to the bottom of it because apparently this should not be happening.

**Comment by Hosch250** [comment]
What would it take to make this an addin for VS rather than a NuGet package?  I would really rather having VSD as an addin because then I would not need to add it to each project, then remove it before each PR (or hope the repo owner doesn't notice it).

**Comment by Vannevelj** [comment]
Tracked in #482
