### ISSUE TITLE
Implement OnPropertyChangedWithoutCallerMemberName analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#86]
We've already got support for changing a `string` argument to use `nameof()` in combination with `OnPropertyChanged()`, now add an alternative to omit the argument altogether and instead change (if needed) the `OnPropertyChanged(string prop)`'s signature to `OnPropertyChanged([CallerMemberName] string prop = null;`

**Comment by Vannevelj** [comment]
I imagine it would be something like this:

1. Trigger on class definitions
2. Check if the class implements `INotifyPropertyChanged`
3. Check if it already implemented `OnPropertyChanged(string)`
4. Check if the string argument already has a [CallerMemberName]` attribute and a default value of `""` (an empty string)
5. Each invocation that invocates `OnPropertyChanged` should now pass in no arguments

An important note: the interface `INotifyPropertyChanged` doesn't actually define a method -- it's just convention that people use the name `OnPropertyChanged`. Since we can't know which name people will use, we can only check for this one.
However this also means that the method signature is entirely open for them to use: it might have more than one parameter.

I suggest we don't go deep with this: if there is more than one parameter, we won't provide a fix. Only when the method signature looks like `OnPropertyChanged(string)`, we'll handle it. Note that this doesn't say anything about pre-existing attributes or default values.

**Comment by Hosch250** [comment]
Note to self - read this: http://blogs.msdn.com/b/csharpfaq/archive/2012/02/06/implementing-a-code-action-using-roslyn.aspx
