### ISSUE TITLE
Implement NoExplicitAccessModifier analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#87]
Give each field, property, class, etc their explicit access modifier. Nobody wants to remember that.. Case in point: research what all the default access modifiers are and update this issue.

**Comment by Vannevelj** [comment]
I'm delaying this to a next release. I'm leaving on vacation soon and I want 1.7.0 to be released so a bunch of bugs are taken care of.

**Comment by Hosch250** [comment]
This page states what the defaults are: https://msdn.microsoft.com/en-us/library/ms173121.aspx

**Comment by Hosch250** [comment]
This is the list:

1. Class and Struct and internal, members of classes and structs are private (included nested structs/classes).
2. User-defined operators must always be declared as public.
3. Destructors cannot have accessibility modifiers.
4. Interfaces default to internal access.
5. Interface members are always public. No access modifiers can be applied to interface members.
6. Enumeration members are always public, and no access modifiers can be applied.
7. Delegates behave like classes and structs. By default, they have internal access when declared directly within a namespace, and private access when nested.
