### ISSUE TITLE
Implement StringPlaceholdersInWrongOrder analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#90]
The numerical placeholders in a string should count upwards from 0 to n - 1.

Go from this:

    string.Format("abc {2} def {0} ghi {1}", x, y, z);

to this:

    string.Format("abc {0} def {1} ghi {2}", z, x, y);

**Comment by Hosch250** [comment]
This should be tested with this use case also:

    string.Format("abc {0} def {1} ghi {2} def {1} abc {0}", y, z, x);
